"use client";

import { motion } from "framer-motion";

const features = [
  {
    title: "Security-first",
    description:
      "JWT authentication, input validation, rate limiting, CORS, security headers. All configured correctly from day one.",
    highlight: "Built by security engineers",
    gradient: "from-emerald-500 to-cyan-500",
    gradientText: "from-emerald-400 to-cyan-400", // Brighter for text contrast on dark bg
  },
  {
    title: "Production-ready",
    description:
      "Not empty scaffolding. Fully implemented routes, error handling, logging, health checks. Could deploy immediately.",
    highlight: "Deploy on day one",
    gradient: "from-cyan-500 to-blue-500",
    gradientText: "from-cyan-400 to-blue-400",
  },
  {
    title: "You own the code",
    description:
      "Download a zip. Host anywhere. Modify anything. No vendor lock-in, no monthly platform fees, no limits.",
    highlight: "Zero lock-in",
    gradient: "from-blue-500 to-violet-500",
    gradientText: "from-blue-400 to-violet-400",
  },
  {
    title: "Complete package",
    description:
      "Code, tests, documentation, Docker config, environment templates. Everything you need in one export.",
    highlight: "Tests included",
    gradient: "from-violet-500 to-pink-500",
    gradientText: "from-violet-400 to-pink-400",
  },
];

const securityFeatures = [
  "JWT with refresh tokens",
  "Zod input validation",
  "Rate limiting",
  "CORS configuration",
  "Security headers",
  "SQL injection prevention",
];

export function Features() {
  return (
    <section className="relative py-24 px-6 bg-zinc-950">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            What you get
          </h2>
          <p className="text-zinc-400 max-w-xl mx-auto">
            Every backend generated by InstAPI is secure, tested, and ready for
            production.
          </p>
        </motion.div>

        {/* Main features grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-16">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="group relative"
            >
              {/* Card with gradient left border */}
              <div className="relative h-full bg-zinc-900/40 backdrop-blur-sm rounded-xl p-6 border border-zinc-800/50 hover:border-zinc-700/50 transition-all overflow-hidden">
                {/* Gradient accent line */}
                <div
                  className={`absolute left-0 top-0 bottom-0 w-1 bg-gradient-to-b ${feature.gradient} opacity-60 group-hover:opacity-100 transition-opacity`}
                />

                {/* Content */}
                <div className="pl-4">
                  <div className="flex items-center justify-between mb-3">
                    <h3 className="text-lg font-semibold text-white">
                      {feature.title}
                    </h3>
                    <span className="relative text-xs font-medium rounded-full overflow-hidden">
                      {/* Gradient border */}
                      <span
                        className={`absolute inset-0 bg-gradient-to-r ${feature.gradient} rounded-full`}
                      />
                      {/* Dark inner background */}
                      <span className="absolute inset-[1px] bg-zinc-900 rounded-full" />
                      {/* Gradient text - high contrast on dark bg */}
                      <span
                        className={`relative block px-2.5 py-1 bg-gradient-to-r ${feature.gradientText} bg-clip-text text-transparent`}
                      >
                        {feature.highlight}
                      </span>
                    </span>
                  </div>
                  <p className="text-sm text-zinc-400 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Security section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="relative overflow-hidden rounded-xl"
        >
          {/* Gradient border effect */}
          <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/20 via-cyan-500/20 to-blue-500/20 rounded-xl" />
          <div className="absolute inset-[1px] bg-zinc-900/90 rounded-xl" />

          <div className="relative p-8">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-8">
              <div className="lg:max-w-md">
                <h3 className="text-xl font-semibold text-white mb-2">
                  Security isn&apos;t optional
                </h3>
                <p className="text-sm text-zinc-400">
                  Every InstAPI backend includes security best practices built
                  in. Not as an afterthought. Not as a paid add-on.
                </p>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                {securityFeatures.map((feature, index) => (
                  <motion.div
                    key={feature}
                    initial={{ opacity: 0, scale: 0.9 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.3, delay: index * 0.05 }}
                    className="flex items-center gap-2 px-3 py-2 bg-zinc-800/30 border border-zinc-700/30 rounded-lg"
                  >
                    <div className="w-4 h-4 flex-shrink-0 flex items-center justify-center rounded-full bg-gradient-to-br from-emerald-600 to-teal-600">
                      <svg
                        className="w-2.5 h-2.5 text-white"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={3}
                          d="M5 13l4 4L19 7"
                        />
                      </svg>
                    </div>
                    <span className="text-xs text-zinc-300 whitespace-nowrap">
                      {feature}
                    </span>
                  </motion.div>
                ))}
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
